[tool.poetry]
name = "dcr-django-test"
version = "0.1.0"
description = ""
authors = ["y"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "2.2.17"
pytz = "2020.5"
sqlparse = "0.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
